use alloc::string::String;
use core::fmt;
#[derive(Debug, Clone, PartialEq)]
pub struct Token {
    pub kind: TokenKind,
    pub lexeme: String,
    pub line: usize,
    pub column: usize,
}

impl Token {
    pub fn new(kind: TokenKind, lexeme: String, line: usize, column: usize) -> Self {
        Self {
            kind,
            lexeme,
            line,
            column,
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum TokenKind {
    Integer,
    Float,
    String,
    True,
    False,
    Identifier,
    Local,
    Mut,
    Function,
    Return,
    If,
    Then,
    Else,
    Elseif,
    End,
    While,
    Do,
    For,
    In,
    Break,
    Continue,
    Struct,
    Enum,
    Trait,
    Impl,
    Match,
    Case,
    As,
    Is,
    Extern,
    Unsafe,
    Pub,
    Use,
    Module,
    Const,
    Static,
    Type,
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    Caret,
    DoubleDot,
    Concat,
    Equal,
    DoubleEqual,
    NotEqual,
    Less,
    LessEqual,
    Greater,
    GreaterEqual,
    And,
    Or,
    Not,
    PlusEqual,
    MinusEqual,
    StarEqual,
    SlashEqual,
    Ampersand,
    Pipe,
    Question,
    LeftParen,
    RightParen,
    LeftBrace,
    RightBrace,
    LeftBracket,
    RightBracket,
    Comma,
    Colon,
    DoubleColon,
    Semicolon,
    Dot,
    Arrow,
    FatArrow,
    Comment,
    Whitespace,
    Newline,
    Eof,
}

impl fmt::Display for TokenKind {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            TokenKind::Integer => write!(f, "integer"),
            TokenKind::Float => write!(f, "float"),
            TokenKind::String => write!(f, "string"),
            TokenKind::True => write!(f, "true"),
            TokenKind::False => write!(f, "false"),
            TokenKind::Identifier => write!(f, "identifier"),
            TokenKind::Local => write!(f, "local"),
            TokenKind::Mut => write!(f, "mut"),
            TokenKind::Function => write!(f, "function"),
            TokenKind::Return => write!(f, "return"),
            TokenKind::If => write!(f, "if"),
            TokenKind::Then => write!(f, "then"),
            TokenKind::Else => write!(f, "else"),
            TokenKind::Elseif => write!(f, "elseif"),
            TokenKind::End => write!(f, "end"),
            TokenKind::While => write!(f, "while"),
            TokenKind::Do => write!(f, "do"),
            TokenKind::For => write!(f, "for"),
            TokenKind::In => write!(f, "in"),
            TokenKind::Break => write!(f, "break"),
            TokenKind::Continue => write!(f, "continue"),
            TokenKind::Struct => write!(f, "struct"),
            TokenKind::Enum => write!(f, "enum"),
            TokenKind::Trait => write!(f, "trait"),
            TokenKind::Impl => write!(f, "impl"),
            TokenKind::Match => write!(f, "match"),
            TokenKind::Case => write!(f, "case"),
            TokenKind::As => write!(f, "as"),
            TokenKind::Is => write!(f, "is"),
            TokenKind::Extern => write!(f, "extern"),
            TokenKind::Unsafe => write!(f, "unsafe"),
            TokenKind::Pub => write!(f, "pub"),
            TokenKind::Use => write!(f, "use"),
            TokenKind::Module => write!(f, "module"),
            TokenKind::Const => write!(f, "const"),
            TokenKind::Static => write!(f, "static"),
            TokenKind::Type => write!(f, "type"),
            TokenKind::Plus => write!(f, "+"),
            TokenKind::Minus => write!(f, "-"),
            TokenKind::Star => write!(f, "*"),
            TokenKind::Slash => write!(f, "/"),
            TokenKind::Percent => write!(f, "%"),
            TokenKind::Caret => write!(f, "^"),
            TokenKind::DoubleDot => write!(f, ".."),
            TokenKind::Concat => write!(f, ".."),
            TokenKind::Equal => write!(f, "="),
            TokenKind::DoubleEqual => write!(f, "=="),
            TokenKind::NotEqual => write!(f, "~="),
            TokenKind::Less => write!(f, "<"),
            TokenKind::LessEqual => write!(f, "<="),
            TokenKind::Greater => write!(f, ">"),
            TokenKind::GreaterEqual => write!(f, ">="),
            TokenKind::And => write!(f, "and"),
            TokenKind::Or => write!(f, "or"),
            TokenKind::Not => write!(f, "not"),
            TokenKind::PlusEqual => write!(f, "+="),
            TokenKind::MinusEqual => write!(f, "-="),
            TokenKind::StarEqual => write!(f, "*="),
            TokenKind::SlashEqual => write!(f, "/="),
            TokenKind::Ampersand => write!(f, "&"),
            TokenKind::Pipe => write!(f, "|"),
            TokenKind::Question => write!(f, "?"),
            TokenKind::LeftParen => write!(f, "("),
            TokenKind::RightParen => write!(f, ")"),
            TokenKind::LeftBrace => write!(f, "{{"),
            TokenKind::RightBrace => write!(f, "}}"),
            TokenKind::LeftBracket => write!(f, "["),
            TokenKind::RightBracket => write!(f, "]"),
            TokenKind::Comma => write!(f, ","),
            TokenKind::Colon => write!(f, ":"),
            TokenKind::DoubleColon => write!(f, "::"),
            TokenKind::Semicolon => write!(f, ";"),
            TokenKind::Dot => write!(f, "."),
            TokenKind::Arrow => write!(f, "->"),
            TokenKind::FatArrow => write!(f, "=>"),
            TokenKind::Comment => write!(f, "comment"),
            TokenKind::Whitespace => write!(f, "whitespace"),
            TokenKind::Newline => write!(f, "newline"),
            TokenKind::Eof => write!(f, "EOF"),
        }
    }
}

impl TokenKind {
    pub fn keyword(s: &str) -> Option<TokenKind> {
        match s {
            "local" => Some(TokenKind::Local),
            "mut" => Some(TokenKind::Mut),
            "function" => Some(TokenKind::Function),
            "return" => Some(TokenKind::Return),
            "if" => Some(TokenKind::If),
            "then" => Some(TokenKind::Then),
            "else" => Some(TokenKind::Else),
            "elseif" => Some(TokenKind::Elseif),
            "end" => Some(TokenKind::End),
            "while" => Some(TokenKind::While),
            "do" => Some(TokenKind::Do),
            "for" => Some(TokenKind::For),
            "in" => Some(TokenKind::In),
            "break" => Some(TokenKind::Break),
            "continue" => Some(TokenKind::Continue),
            "struct" => Some(TokenKind::Struct),
            "enum" => Some(TokenKind::Enum),
            "trait" => Some(TokenKind::Trait),
            "impl" => Some(TokenKind::Impl),
            "match" => Some(TokenKind::Match),
            "case" => Some(TokenKind::Case),
            "as" => Some(TokenKind::As),
            "is" => Some(TokenKind::Is),
            "true" => Some(TokenKind::True),
            "false" => Some(TokenKind::False),
            "and" => Some(TokenKind::And),
            "or" => Some(TokenKind::Or),
            "not" => Some(TokenKind::Not),
            "extern" => Some(TokenKind::Extern),
            "unsafe" => Some(TokenKind::Unsafe),
            "pub" => Some(TokenKind::Pub),
            "use" => Some(TokenKind::Use),
            "module" => Some(TokenKind::Module),
            "const" => Some(TokenKind::Const),
            "static" => Some(TokenKind::Static),
            "type" => Some(TokenKind::Type),
            _ => None,
        }
    }
}
